### ISSUE TITLE
Unclear how to determine job completion from get_state response.

### ISSUE THREAD

**Issue by cjkrome** [pacifica/pacifica-ingest#64]
For the ingest get_state call, it's not very clear how to determine if the process is complete. The _task_percent_ field in the response only indicates the status of the current task, and the _state_ field is always set to OK (unless an error occurred). As it stands, the only way to tell the process has finished is to check that the _task_ is "ingest metadata" and the _task_percent_ is 100.

**Comment by dmlb2000** [comment]
@cjkrome as I don't like percentages, years of badly programmed progress bars are to blame for that. Would a task completed flag be appropriate? Would that flag be set if there's an error or successful completion?
