### ISSUE TITLE
ORM Database creation script not autogenerating tables in postgresql

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-ingest#67]
### Pacifica Ingest version
latest

### Scenario:
trying to autogenerate database schema via ORM python tooling provided

### Steps to Reproduce:
install pacifica-ingest with pip
Setup env and configs
attempt to start service script which includes:
`python -c 'from pacifica.ingest.orm import create_tables; create_tables()'`

### Expected Result:
if database is blank, create tables as necessary
if database exists, update tables to reflect current schema or close to this result

### Actual Result:
no tables are created

**Comment by GitBytes** [comment]
Found some additional logging to narrow down the issue:
```
Nov 27 14:39:08 core pacifica-ingest-frontend[11055]: """)
Nov 27 14:39:08 core pacifica-ingest-frontend[11055]: Traceback (most recent call last):
Nov 27 14:39:08 core pacifica-ingest-frontend[11055]: File "<string>", line 1, in <module>
Nov 27 14:39:08 core pacifica-ingest-frontend[11055]: ImportError: cannot import name create_tables
```

**Comment by dmlb2000** [comment]
Right now this is `database_setup()` but we need to standardize on this and use a command line tool to manage the database.
