### ISSUE TITLE
Has test env in travis been updated to reflect changes made in release 0.3.0?

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-ingest#75]
https://github.com/pacifica/pacifica-ingest/blob/5e45364d00fda51c03624fc954b5bac8fe93941f/.travis.yml#L28-L29

**Comment by dmlb2000** [comment]
The way to create the database at that version is by calling out to the python method `database_setup()`. Then we call out to pip to upgrade the software stack and verify the methods for checking and updating the database are working.
